# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'
  pull_request:
    branches:
      - main  # Run on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the repository code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify the Python version
    
      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -  # Install Poetry
          export PATH="$HOME/.local/bin:$PATH"  # Add Poetry to PATH
    #      poetry install  # Install dependencies using Poetry
          poetry install --no-root


      # - name: Run tests
      #   run: |
      #     pytest  # Run your tests using pytest